// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: lib/validator/protobuf/testdata/schema3-1.proto

package testpb3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age        int32       `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Collection []string    `protobuf:"bytes,3,rep,name=collection,proto3" json:"collection,omitempty"`
	Foo        *Record_Foo `protobuf:"bytes,4,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Record) GetCollection() []string {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *Record) GetFoo() *Record_Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

type Record_Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bar string `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
}

func (x *Record_Foo) Reset() {
	*x = Record_Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record_Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record_Foo) ProtoMessage() {}

func (x *Record_Foo) ProtoReflect() protoreflect.Message {
	mi := &file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record_Foo.ProtoReflect.Descriptor instead.
func (*Record_Foo) Descriptor() ([]byte, []int) {
	return file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Record_Foo) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

var File_lib_validator_protobuf_testdata_schema3_1_proto protoreflect.FileDescriptor

var file_lib_validator_protobuf_testdata_schema3_1_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x33, 0x2d, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x33, 0x22, 0x90, 0x01, 0x0a,
	0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x03, 0x66, 0x6f, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x33, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x46, 0x6f,
	0x6f, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x1a, 0x17, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x62, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x61, 0x72, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x33, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescOnce sync.Once
	file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescData = file_lib_validator_protobuf_testdata_schema3_1_proto_rawDesc
)

func file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescGZIP() []byte {
	file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescOnce.Do(func() {
		file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescData)
	})
	return file_lib_validator_protobuf_testdata_schema3_1_proto_rawDescData
}

var file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_validator_protobuf_testdata_schema3_1_proto_goTypes = []interface{}{
	(*Record)(nil),     // 0: testdata3.Record
	(*Record_Foo)(nil), // 1: testdata3.Record.Foo
}
var file_lib_validator_protobuf_testdata_schema3_1_proto_depIdxs = []int32{
	1, // 0: testdata3.Record.foo:type_name -> testdata3.Record.Foo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_validator_protobuf_testdata_schema3_1_proto_init() }
func file_lib_validator_protobuf_testdata_schema3_1_proto_init() {
	if File_lib_validator_protobuf_testdata_schema3_1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record_Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_validator_protobuf_testdata_schema3_1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_validator_protobuf_testdata_schema3_1_proto_goTypes,
		DependencyIndexes: file_lib_validator_protobuf_testdata_schema3_1_proto_depIdxs,
		MessageInfos:      file_lib_validator_protobuf_testdata_schema3_1_proto_msgTypes,
	}.Build()
	File_lib_validator_protobuf_testdata_schema3_1_proto = out.File
	file_lib_validator_protobuf_testdata_schema3_1_proto_rawDesc = nil
	file_lib_validator_protobuf_testdata_schema3_1_proto_goTypes = nil
	file_lib_validator_protobuf_testdata_schema3_1_proto_depIdxs = nil
}
